# Generated by Django 6.0.3 on 2026-03-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_telegram_chat_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telegram_chat_id",
        ),
    ]
