# Generated by Django 6.0.3 on 2026-03-15 07:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=255)),
                ("place", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                ("is_pleasant", models.BooleanField(default=False)),
                ("reward", models.CharField(blank=True, max_length=255)),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                ("duration", models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120)])),
                ("is_public", models.BooleanField(default=False)),
                ("last_reminded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_habits",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "ordering": ("time", "id"),
            },
        ),
    ]
