# Generated by Django 6.0.3 on 2026-03-22 07:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="habit",
            new_name="habits_habi_user_id_0c9228_idx",
            old_name="habits_habi_user_id_1cfbea_idx",
        ),
        migrations.RenameIndex(
            model_name="habit",
            new_name="habits_habi_is_publ_af85bc_idx",
            old_name="habits_habi_is_publ_420eb9_idx",
        ),
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(help_text="Что именно нужно сделать", max_length=255, verbose_name="Действие"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveSmallIntegerField(
                help_text="Время выполнения в секундах, не более 120",
                validators=[django.core.validators.MaxValueValidator(120)],
                verbose_name="Длительность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False, help_text="Можно использовать как вознаграждение", verbose_name="Приятная привычка"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="last_reminded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время последнего напоминания",
                null=True,
                verbose_name="Последнее напоминание",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Периодичность в днях: от 1 до 7",
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)],
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Связанная приятная привычка",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_habits",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Текстовое вознаграждение",
                max_length=255,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
